### PR TITLE
Remove "applyfrom" to achieve symmetry with "apply plugin"

### LINKED ISSUE #442: [Feature Request] - "applyplugin"
There is the following for scripts:
```
apply {
  from("script.gradle")
}
```
and 
```
applyfrom("script.gradle")
```

There is the following plugins:
```
apply {
  plugin("java-library")
  plugin("kotlin")
}
```
but there is no
```
applyplugin("java-library")
```

Could we add in `applyplugin`?

### PR DESCRIPTION
**Pull request by jaredsburrows**
@bamboo @eskatos @JakeWharton
Closes #442

### CODE REVIEW

**Comment by bamboo** [comment]
Thanks for the PR, @jaredsburrows. Could you re-post it against the `develop` branch though?

We haven't documented this yet but development now takes place in `develop` and we keep `master` in sync with the last release.

**Comment by jaredsburrows** [comment]
@bamboo I cannot edit the branch. I will have to close this. Can you make this repo show `develop` as the default? I did not see that I should be sending PRs against `develop`.

**Comment by bamboo** [comment]
Unfortunately changing the default branch to `develop` doesn't have the exact effect we intend.

We'll make sure to include that information in the PR template though.

**Comment by jaredsburrows** [comment]
@bamboo Thanks.

**Pull request closed without merging**
