### PR TITLE
Fix Groovy Interop with null receiving closures

### LINKED ISSUE #593: KotlinClosure1 and similar can not specify null recivier
### Expected Behavior
Should be able to define a `KotlinClosure1` like this:
```kotlin
KotlinClosure1<Exception?, Unit> ({
    // Do something
}
```
### Current Behavior
Compiler error:
```
MessageBroker.gradle.kts:46:30: Type argument is not within its bounds: should be subtype of 'Any'
```

### Your Environment
```
------------------------------------------------------------
Gradle 4.3.1
------------------------------------------------------------

Build time:   2017-11-08 08:59:45 UTC
Revision:     e4f4804807ef7c2829da51877861ff06e07e006d

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_92 (Oracle Corporation 25.92-b14)
OS:           Mac OS X 10.12.6 x86_64

```

### PR DESCRIPTION
**Pull request by JLLeitschuh**
Closes #593

### Contributor Checklist
- [x] Base the PR against the `develop` branch
- [x] [Sign Gradle CLA](http://gradle.org/contributor-license-agreement/)
- [x] Provide integration tests to verify changes from a user perspective
- [x] Provide unit tests to verify logic
- [x] Ensure that tests pass locally: `./gradlew check --parallel`

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
Why is everything in the `` file specifying the types as `T : Any`, why are they all saying that they are of type `Any`? Couldn't the `Any` be dropped from most of these generics and also solve this nullability problem?

**Comment by JLLeitschuh** [comment]
@bamboo Looks like there's a compilation issue on JDK 9? Looking at the travis logs:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/home/travis/.gradle/wrapper/dists/gradle-kotlin-dsl-4.4-20171114142330+0000-all/7q5islb3aza0kaq3uk7giu4jc/gradle-4.4-20171114142330+0000/lib/groovy-all-2.4.12.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
org.gradle.kotlin.dsl.provider.KotlinScriptClassPathProviderTest > should report progress based on the number of entries in gradle-api jar STANDARD_ERROR
    e: /tmp/kotlin-dsl-extensions14583642004776219987jar11075150926074467559/org/gradle/kotlin/dsl/BuiltinPluginIdExtensions.kt:19:19: Unresolved reference: plugin
    e: /tmp/kotlin-dsl-extensions14583642004776219987jar11075150926074467559/org/gradle/kotlin/dsl/BuiltinPluginIdExtensions.kt:20:19: Unresolved reference: plugin
Gradle Test Executor 1 finished executing tests.
```

**Comment by JLLeitschuh** [comment]
Can someone re-kick this travis job to see if it clears itself up?

**Comment by bamboo** [comment]
Travis build job restarted.

**Comment by JLLeitschuh** [comment]
This looks like it works fine now.
@bamboo Mind reviewing?

**Comment by bamboo** [comment]
Thanks for the PR, @JLLeitschuh!

**Pull request merged**
