### PR TITLE
Expose `kotlin-stdlib-jre8` to build scripts

### PR DESCRIPTION
**Pull request by bamboo**
See #558

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
Can you make sure that this is rebased on top of the `develop` branch so that JDK 9 travis fix is in there??

**Comment by JLLeitschuh** [comment]
So you ran the Open JDK build twice (once as a push check and once as a PR check).

One of the openJDK build tests fails with what looks like a compile error but Its hard to tell.
I'm confused why it fails once but not the other time.
https://travis-ci.org/gradle/kotlin-dsl/jobs/290168068

**Comment by bamboo** [comment]
@eskatos done. Looks like a Kotlin bug to me.

**Comment by eskatos** [comment]
Indeed. Mind finding/opening an issue upstream?

**Comment by JLLeitschuh** [comment]
> Retrieving groups by name is not supported on this platform.

That is really strange.

**Comment by bamboo** [comment]
Follow-up Kotlin YT issue: https://youtrack.jetbrains.com/issue/KT-20865

**Pull request merged**
