### PR TITLE
Allow access to Gradle properties from settings.gradle.kts files

### PR DESCRIPTION
**Pull request by araqnid**
Signed-off-by: Steve Haslam <steve.haslam@timgroup.com>

### Context

We currently specify the path to our local repo using a gradle.properties file for our CI user, and in
the Groovy DSL can simply read these in settings.gradle. There are already ways to access this from the project, but it needs to be accessible from settings to allow the repo to be used for plugin resolution.

https://github.com/gradle/kotlin-dsl/issues/635

### Contributor Checklist
- [x] Base the PR against the `develop` branch
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Provide integration tests to verify changes from a user perspective
- [ ] Provide unit tests to verify logic
- [x] Ensure that tests pass locally: `./gradlew check --parallel`

### CODE REVIEW

**Comment by araqnid** [comment]
I can't reproduce the Travis failure locally :(

**Comment by bamboo** [comment]
Thanks for the PR. We should enable access to Gradle properties without involving reflection though.

Blocked by #660

**Comment by bamboo** [comment]
Superseded by #653.

**Comment by JLLeitschuh** [comment]
@bamboo You have this listed as Superseded by itself? I think you meant some other issue number.

**Comment by eskatos** [comment]
Right, this one is superseded by #635

**Pull request closed without merging**
