### PR TITLE
Remove "applyfrom" to achieve symmetry with "apply plugin"

### LINKED ISSUE #442: [Feature Request] - "applyplugin"
There is the following for scripts:
```
apply {
  from("script.gradle")
}
```
and 
```
applyfrom("script.gradle")
```

There is the following plugins:
```
apply {
  plugin("java-library")
  plugin("kotlin")
}
```
but there is no
```
applyplugin("java-library")
```

Could we add in `applyplugin`?

### PR DESCRIPTION
**Pull request by jaredsburrows**
@bamboo @eskatos @JakeWharton
Closes #442

### CODE REVIEW

**Comment by jaredsburrows** [comment]
@bamboo Now sending PR to `develop` instead of `master`. Previous PR: https://github.com/gradle/kotlin-dsl/pull/444.

**Comment by jaredsburrows** [comment]
@bamboo I cannot see the build status. Locally everything is fine. Is it good on TC?

**Comment by jaredsburrows** [comment]
@bamboo The Travis build is not being triggered for the `develop` branch.

**Comment by bamboo** [comment]
@jaredsburrows The Travis build has been broken forever :/

**Comment by bamboo** [comment]
Thanks for the PR, @jaredsburrows!

**Pull request merged**
