### PR TITLE
Samples and build use settings.gradle.kts

### PR DESCRIPTION
**Pull request by eskatos**
See #550

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
Android studio requires that a `build.gradle` file exists. It doesn't have the same requirement for `settings.gradle` to exist correct?

**Comment by JLLeitschuh** [comment]
Another question, when developing composite build projects the project that you are targeting in an `includeBuild` call requires that targeted project have a `settings.gradle` file (you get an exception if you don't).

Two questions:
 1. Have you tested that a composite build project with a `settings.gradle.kts` file and without a `settings.gradle` file works correctly?
 2. Has the exception mentioning that you must have a `settings.gradle` file been updated to state that you need either a `settings.gradle` or a `settings.gradle.kts` file?

**Comment by bamboo** [comment]
> Android studio requires that a build.gradle file exists. It doesn't have the same requirement for settings.gradle to exist correct?

That's a good question.

**Comment by JLLeitschuh** [comment]
I've opened an issue with TravisCI about all of the JDK 9 builds failing:
https://github.com/travis-ci/travis-ci/issues/8608

**Comment by eskatos** [comment]
> Android studio requires that a build.gradle file exists. It doesn't have the same requirement for settings.gradle to exist correct?

Correct. I validated that project import and usage in Android Studio is working.

> Another question, when developing composite build projects the project that you are targeting in an includeBuild call requires that targeted project have a settings.gradle file (you get an exception if you don't).
>
> Two questions:
> - Have you tested that a composite build project with a settings.gradle.kts file and without a settings.gradle file works correctly?
> - Has the exception mentioning that you must have a settings.gradle file been updated to state that you need either a settings.gradle or a settings.gradle.kts file?

Yes, this has been handled upstream in Gradle.

**Pull request merged**
