### PR TITLE
Prefer plugin portal over repo.gradle.org

### PR DESCRIPTION
**Pull request by eskatos**
Because of https://youtrack.jetbrains.com/issue/KT-22974

### CODE REVIEW

**Comment by bamboo** [comment]
Is that better than fixing `repo.gradle.org`?

**Comment by eskatos** [comment]
@bamboo Fixing `repo.gradle.org` would mean making it mirror the plugin portal, right?
This could be considered.
But making our build consume the plugin portal instead makes sense to me.

**Comment by eskatos** [comment]
I also guess that "fixing `repo.gradle.org` won't fix our present issue because of the checksums mismatch.

**Comment by bamboo** [comment]
By fixing `repo.gradle.org` I mean making it serve the right Kotlin artifacts, however we do it.

It doesn't feel right to build against the plugin portal for a few reasons but mainly because we can depend on dev versions with `repo.gradle.org` but not with the portal as the main repo.

**Pull request merged**
