### PR TITLE
Fix typo in pull request template

### PR DESCRIPTION
**Pull request by mkobit**
### Contributor Checklist
- [] Base the PR against the `develop` branch
- [x] Make sure that all commmits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] Provide integration tests to verify changes from a user perspective
- [ ] Provide unit tests to verify logic
- [ ] Ensure that tests pass locally: `./gradlew check --parallel`

### CODE REVIEW

**Comment by eskatos** [comment]
Good catch @mkobit!
Could you re-target the PR to `develop`? it'll then get to `master` later.

**Comment by mkobit** [comment]
Hey @eskatos there were a couple reasons I targeted `master` instead of `develop` (should have just mentioned them in the description, my mistake):

* https://github.com/gradle/kotlin-dsl/blob/develop/.github/PULL_REQUEST_TEMPLATE.md - the `develop` branch PR template has the older recommendation of CLA and I didn't want to do any cherry-picking / back merging of https://github.com/gradle/kotlin-dsl/commit/e6b9463a68c0339ee612498d7c3ebbdddded4740
* I think since `master` is the default branch, its `PULL_REQUEST_TEMPLATE.md` template is used instead of the `develop` branch

**Comment by bamboo** [comment]
Thanks for the heads-up @mkobit, the PR template on develop has been updated.

**Comment by bamboo** [comment]
Fixed in a5de7d1b485ae30755d4ac09e54063cd9e9678e3 and 74f5b7e4479499487f8077ce586cf7fda7d7e11f. Thanks again!

**Pull request closed without merging**
